language: csharp
solution: ./Sources/Ditch.sln
before_script:
- cp .\Sources\Ditch.BitShares.Tests\app.config.template .\Sources\Ditch.BitShares.Tests\app.config
- cp .\Sources\Ditch.Core.Tests\app.config.template .\Sources\Ditch.Core.Tests\app.config
- cp .\Sources\Ditch.EOS.Tests\app.config.template .\Sources\Ditch.EOS.Tests\app.config
- cp .\Sources\Ditch.Ethereum.Tests\app.config.template .\Sources\Ditch.Ethereum.Tests\app.config
- cp .\Sources\Ditch.Golos.Tests\app.config.template .\Sources\Ditch.Golos.Tests\app.config
- cp .\Sources\Ditch.Steem.Tests\app.config.template .\Sources\Ditch.Steem.Tests\app.config